#include "ip.h"
#include "icmp.h"
#include "packet.h"
#include "arpcache.h"
#include "rtable.h"
#include "arp.h"

#include "log.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// initialize ip header 
void ip_init_hdr(struct iphdr *ip, u32 saddr, u32 daddr, u16 len, u8 proto)
{
	ip->version = 4;
	ip->ihl = 5;
	ip->tos = 0;
	ip->tot_len = htons(len);
	ip->id = rand();
	ip->frag_off = htons(IP_DF);
	ip->ttl = DEFAULT_TTL;
	ip->protocol = proto;
	ip->saddr = htonl(saddr);
	ip->daddr = htonl(daddr);
	ip->checksum = ip_checksum(ip);
}

// lookup in the routing table, to find the entry with the same and longest prefix.
// the input address is in host byte order
rt_entry_t *longest_prefix_match(u32 dst)
{
	rt_entry_t *entry = NULL;
	u32 longest_mask = 0;
	rt_entry_t *longest_entry = NULL;
	list_for_each_entry(entry, &rtable, list) {
		if (((dst & entry->mask) == (entry->dest & entry->mask)) && entry->mask > longest_mask) {
			longest_mask = entry->mask;
			longest_entry = entry;
		}
	}
	return longest_entry;
}

// send IP packet
//
// Different from forwarding packet, ip_send_packet sends packet generated by
// router itself. This function is used to send ICMP packets.
void ip_send_packet(char *packet, int len)
{
	struct iphdr *ip = packet_to_ip_hdr(packet);
	rt_entry_t *entry = longest_prefix_match(ntohl(ip->daddr));
	if (!entry) {
		// free(packet);
		return;
	}

	u32 next_hop = entry->gw ? entry->gw : ntohl(ip->daddr);
	struct ether_header *eh = (struct ether_header *)packet;
	eh->ether_type = ntohs(ETH_P_IP);
	memcpy(eh->ether_shost, entry->iface->mac, ETH_ALEN);

	iface_send_packet_by_arp(entry->iface, next_hop, packet, len);
	// log(DEBUG, "");
}
